/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTG6 (number 51), SPI_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_MISO_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_MISO_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_MISO_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTG5 (number 52), SPI_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_MOSI_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_MOSI_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_MOSI_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTG4 (number 53), SPI_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_SCK_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SCK_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SCK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTI3 (number 65), SPI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FLASH_CS_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_FLASH_CS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_FLASH_CS_GPIO_PORT kGPIO_PORTI    /*!<@brief PORTC GPIO port: PORTC */
#define BOARD_INITPINS_FLASH_CS_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_FLASH_CS_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FLASH_CS_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FLASH_CS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA0 (number 62), SPI_WP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPI_WP_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SPI_WP_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPI_WP_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_SPI_WP_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_WP_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_WP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_WP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA1 (number 61), SPI_HOLD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPI_HOLD_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SPI_HOLD_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPI_HOLD_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_SPI_HOLD_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_HOLD_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_HOLD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_HOLD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
