/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_spi.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SPI1 */
/* Definition of peripheral ID */
#define SPI1_PERIPHERAL SPI1
/* Definition of the clock source */
#define SPI1_CLOCK_SOURCE SPI1_CLK_SRC
/* Definition of the clock source frequency */
#define SPI1_CLK_FREQ 24000000UL
/* SPI1 interrupt vector ID (number). */
#define SPI1_IRQN SPI1_IRQn
/* Transfer buffer size. */
#define SPI1_BUFFER_SIZE 10

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const spi_master_config_t SPI1_config;
extern spi_master_handle_t SPI1_handle;
extern uint8_t SPI1_txBuffer[SPI1_BUFFER_SIZE];
extern uint8_t SPI1_rxBuffer[SPI1_BUFFER_SIZE];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
