/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: MKE06Z128xxx4
package_id: MKE06Z128VLK4
mcu_data: ksdk2_0
processor_version: 13.0.1
pin_labels:
- {pin_num: '51', pin_signal: PTG6/KBI1_P22/FTM2_CH4/SPI1_MISO, label: SPI_MISO, identifier: SPI_MISO}
- {pin_num: '52', pin_signal: PTG5/KBI1_P21/FTM2_CH3/SPI1_MOSI, label: SPI_MOSI, identifier: SPI_MOSI}
- {pin_num: '53', pin_signal: PTG4/KBI1_P20/FTM2_CH2/SPI1_SCK, label: SPI_SCK, identifier: SPI_SCK}
- {pin_num: '65', pin_signal: PTI3/IRQ, label: SPI, identifier: SPI;FLASH_CS}
- {pin_num: '62', pin_signal: PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0, label: SPI_WP, identifier: SPI_WP}
- {pin_num: '61', pin_signal: PTA1/KBI0_P1/FTM0_CH1/I2C0_4WSDAOUT/ACMP0_IN1/ADC0_SE1, label: SPI_HOLD, identifier: SPI_HOLD}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '51', peripheral: SPI1, signal: MISO, pin_signal: PTG6/KBI1_P22/FTM2_CH4/SPI1_MISO, direction: INPUT}
  - {pin_num: '52', peripheral: SPI1, signal: MOSI, pin_signal: PTG5/KBI1_P21/FTM2_CH3/SPI1_MOSI, direction: OUTPUT}
  - {pin_num: '53', peripheral: SPI1, signal: SCK, pin_signal: PTG4/KBI1_P20/FTM2_CH2/SPI1_SCK, direction: OUTPUT}
  - {pin_num: '65', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: PTI3/IRQ, identifier: FLASH_CS, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '62', peripheral: GPIOA, signal: 'GPIO, 0', pin_signal: PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0, direction: OUTPUT}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/KBI0_P1/FTM0_CH1/I2C0_4WSDAOUT/ACMP0_IN1/ADC0_SE1, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{

    gpio_pin_config_t SPI_WP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA0 (pin 62) */
    GPIO_PinInit(BOARD_INITPINS_SPI_WP_GPIO_PORT, BOARD_INITPINS_SPI_WP_PIN, &SPI_WP_config);

    gpio_pin_config_t SPI_HOLD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 61) */
    GPIO_PinInit(BOARD_INITPINS_SPI_HOLD_GPIO_PORT, BOARD_INITPINS_SPI_HOLD_PIN, &SPI_HOLD_config);

    gpio_pin_config_t FLASH_CS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 65) */
    GPIO_PinInit(BOARD_INITPINS_FLASH_CS_GPIO_PORT, BOARD_INITPINS_FLASH_CS_PIN, &FLASH_CS_config);
    /* pin 51,52,53 is configured as SPI1_MISO, SPI1_MOSI, SPI1_SCK */
    PORT_SetPinSelect(kPORT_SPI1, kPORT_SPI1_SCKPTG4_MOSIPTG5_MISOPTG6_PCSPTG7);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
